services:
  orders_api:
    build:
      context: ./APIS/orders
    ports:
      - "3001:3000"  # Cambié el puerto para evitar colisión
    volumes:
      - ./APIS/orders:/usr/orderAPI
      - ./infraestructura/prisma:/usr/infraestructura/prisma

  payments_api:
    build:
      context: ./APIS/payments
    ports:
      - "3002:3000"  # Cambié el puerto para evitar colisión
    volumes:
      - ./APIS/payments:/usr/paymentAPI  # Corregí el nombre
      - ./infraestructura/prisma:/usr/infraestructura/prisma

  products_api:
    build:
      context: ./APIS/products
    ports:
      - "3003:3000"  # Cambié el puerto para evitar colisión
    volumes:
      - ./APIS/products:/usr/productAPI
      - ./infraestructura/prisma:/usr/infraestructura/prisma

  shoppingcar_api:  # Cambié el nombre a minúsculas
    build:
      context: ./APIS/shopping_car
    ports:
      - "3004:3000"  # Cambié el puerto para evitar colisión
    volumes:
      - ./APIS/shopping_car:/usr/shoppingCarAPI  # Corregí el nombre
      - ./infraestructura/prisma:/usr/infraestructura/prisma
